In [7]:
import pandas as pd
import numpy as np

In [53]:
#huongdan1
df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col="STT")
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [52]:
#huongdan2
df.tail(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,8.3,...,7.84,8.27,8.29,K,G,G,3.762376,3.737864,4.000000,1
92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,6.9,...,6.17,6.63,7.65,TB,K,K,2.108911,2.145631,3.268571,0
93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,6.1,...,6.10,6.53,6.76,TB,K,K,2.039604,2.048544,2.251429,0
94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,5.8,...,6.53,7.12,6.97,K,K,K,2.465347,2.621359,2.491429,0
95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,7.2,...,6.10,6.71,6.68,TB,K,K,2.039604,2.223301,2.160000,0
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,3.356436,2.912621,2.331429,0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,0.881188,0.708738,1.828571,0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.980198,3.320388,3.291429,1
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,0.108911,0.291262,0.571429,0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,1.207921,1.262136,1.211429,0

In [56]:
#huongdan4
df['DT'].fillna(0, inplace=True)
df

/tmp/ipykernel_5271/3614412352.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DT'].fillna(0, inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [55]:
#huongdan5
df["T1"].fillna(df["T1"].mean(), inplace=True)
df

/tmp/ipykernel_5271/3637168835.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["T1"].fillna(df["T1"].mean(), inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [49]:
#cau 6
diem_cols = ['T1','L1','H1','S1','V1','X1','D1','N1',
             'T2','L2','H2','S2','V2','X2','D2','N2',
             'T6','L6','H6','S6','V6','X6','D6','N6']

for col in diem_cols:
    df[col].fillna(df[col].mean(), inplace=True)
df.isnull().sum()

/tmp/ipykernel_5271/311155578.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

T1         0
L1         0
H1         0
S1         0
V1         0
          ..
XL3        0
US_TBM1    0
US_TBM2    0
US_TBM3    0
KQXT       0
Length: 65, dtype: int64

In [48]:
#cau7
df["TBM1"] = (df["T1"]*2 + df["L1"] + df["H1"] + df["S1"] +
              df["V1"]*2 + df["X1"] + df["D1"] + df["N1"]) / 10

df["TBM2"] = (df["T2"]*2 + df["L2"] + df["H2"] + df["S2"] +
              df["V2"]*2 + df["X2"] + df["D2"] + df["N2"]) / 10

df["TBM3"] = (df["T6"]*2 + df["L6"] + df["H6"] + df["S6"] +
              df["V6"]*2 + df["X6"] + df["D6"] + df["N6"]) / 10
df[["TBM1","TBM2","TBM3"]].head(10)

     TBM1  TBM2  TBM3
STT
1    7.00  7.54  7.01
2    4.69  5.47  5.07
3    5.77  5.38  6.04
4    6.21  5.20  6.88
5    6.50  6.36  6.99
6    7.96  8.54  7.38
7    4.90  5.60  6.01
8    6.80  6.87  7.03
9    6.23  6.72  7.56
10   6.80  7.25  7.03

In [47]:
#8
def xeploai(tbm):
    if tbm < 5:
        return "Y"
    elif tbm < 6.5:
        return "TB"
    elif tbm < 8:
        return "K"
    elif tbm < 9:
        return "G"
    else:
        return "XS"

df["XL1"] = df["TBM1"].apply(xeploai)
df["XL2"] = df["TBM2"].apply(xeploai)
df["XL3"] = df["TBM3"].apply(xeploai)
df[["TBM1","XL1","TBM2","XL2","TBM3","XL3"]].head()

     TBM1 XL1  TBM2 XL2  TBM3 XL3
STT
1    7.00   K  7.54   K  7.01   K
2    4.69   Y  5.47  TB  5.07  TB
3    5.77  TB  5.38  TB  6.04  TB
4    6.21  TB  5.20  TB  6.88   K
5    6.50   K  6.36  TB  6.99   K

In [46]:
#cau9
df["US_TBM1"] = (df["TBM1"] - df["TBM1"].min()) / \
                (df["TBM1"].max() - df["TBM1"].min()) * 4

df["US_TBM2"] = (df["TBM2"] - df["TBM2"].min()) / \
                (df["TBM2"].max() - df["TBM2"].min()) * 4

df["US_TBM3"] = (df["TBM3"] - df["TBM3"].min()) / \
                (df["TBM3"].max() - df["TBM3"].min()) * 4
df[["US_TBM1","US_TBM2","US_TBM3"]].head()

      US_TBM1   US_TBM2   US_TBM3
STT
1    2.930693  3.029126  2.537143
2    0.643564  1.019417  0.320000
3    1.712871  0.932039  1.428571
4    2.148515  0.757282  2.388571
5    2.435644  1.883495  2.514286

In [45]:
#cau10
def kqxt(row):
    if row["KT"] in ["A", "A1"]:
        diem = (row["DH1"]*2 + row["DH2"] + row["DH3"]) / 4

    elif row["KT"] == "B":
        diem = (row["DH1"] + row["DH2"]*2 + row["DH3"]) / 4

    else:
        diem = (row["DH1"] + row["DH2"] + row["DH3"]) / 3

    return 1 if diem >= 5 else 0

df["KQXT"] = df.apply(kqxt, axis=1)
df[["KT","DH1","DH2","DH3","KQXT"]].head()

     KT   DH1   DH2   DH3  KQXT
STT
1    A1  3.25  3.25  4.50     0
2     C  6.00  4.00  3.50     0
3     C  5.00  6.75  4.00     1
4    D1  4.25  4.25  5.25     0
5     A  4.25  4.50  5.00     0